FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
WORKDIR /app

COPY pyproject.toml README.md /app/
COPY src /app/src
COPY scripts /app/scripts
COPY configs /app/configs

RUN pip install --no-cache-dir -e ".[stream]"

CMD ["python", "scripts/run_streaming_job.py", "--config", "configs/base.yaml"]
